### ISSUE TITLE
[Bug] S3 Sync Illegal Location Constraint Exception

### ISSUE THREAD

**Issue by dengmingtong** [awslabs/service-workbench-on-aws#876] opened 2022-01-20 14:27 UTC
**Describe the bug**
I am trying to deploy swb in Hongkong(ap-east-1) region, I got below error after backend component cloudformation is finished.

Serverless: Stack update finished...
Service Information
service: hk-sw-backend
stage: demo
region: ap-east-1
stack: demo-hk-sw-backend
resources: 100
api keys:
  None
endpoints:
  GET - https://pdtq5k3cd4.execute-api.ap-east-1.amazonaws.com/demo/api/authentication/public/provider/configs
  POST - https://pdtq5k3cd4.execute-api.ap-east-1.amazonaws.com/demo/api/authentication/id-tokens
  GET - https://pdtq5k3cd4.execute-api.ap-east-1.amazonaws.com/demo/api
  GET - https://pdtq5k3cd4.execute-api.ap-east-1.amazonaws.com/demo/api/{proxy+}
  POST - https://pdtq5k3cd4.execute-api.ap-east-1.amazonaws.com/demo/api
  POST - https://pdtq5k3cd4.execute-api.ap-east-1.amazonaws.com/demo/api/{proxy+}
  PUT - https://pdtq5k3cd4.execute-api.ap-east-1.amazonaws.com/demo/api
  PUT - https://pdtq5k3cd4.execute-api.ap-east-1.amazonaws.com/demo/api/{proxy+}
  DELETE - https://pdtq5k3cd4.execute-api.ap-east-1.amazonaws.com/demo/api
  DELETE - https://pdtq5k3cd4.execute-api.ap-east-1.amazonaws.com/demo/api/{proxy+}
functions:
  authenticationLayerHandler: hk-sw-backend-demo-authenticationLayerHandler
  openDataScrapeHandler: hk-sw-backend-demo-openDataScrapeHandler
  envStatusPollHandler: hk-sw-backend-demo-envStatusPollHandler
  dataSourceReachabilityHandler: hk-sw-backend-demo-dataSourceReachabilityHandler
  dataSourceReachabilityDailyHandler: hk-sw-backend-demo-dataSourceReachabilityDailyHandler
  awsAccountOnboardingHandler: hk-sw-backend-demo-awsAccountOnboardingHandler
  apiHandler: hk-sw-backend-demo-apiHandler
  workflowLoopRunner: hk-sw-backend-demo-workflowLoopRunner
layers:
  None
S3 Sync: Syncing directories and S3 prefixes...
 
  Illegal Location Constraint Exception ------------------
 
  IllegalLocationConstraintException: The ap-east-1 location constraint is incompatible for the region specific endpoint this request was sent to.
      at Request.extractError (/home/ec2-user/environment/gcr-solutions/service-workbench-on-aws/node_modules/.pnpm/aws-sdk@2.721.0/node_modules/aws-sdk/lib/services/s3.js:837:35)
      at Request.callListeners (/home/ec2-user/environment/gcr-solutions/service-workbench-on-aws/node_modules/.pnpm/aws-sdk@2.721.0/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/home/ec2-user/environment/gcr-solutions/service-workbench-on-aws/node_modules/.pnpm/aws-sdk@2.721.0/node_modules/aws-sdk/lib/sequential_executor.js:78:10)

**To Reproduce**
Deploy swb through cloud9.
After run ./scripts/environment-deploy.sh ${STAGE_NAME}

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Release Version installed [e.g. v1.0.3]

**Additional context**

**Comment by ssvegaraju** [comment] 2022-01-21 20:32
Hi, thanks for bringing this issue up, we will look into this!

**Comment by Bingjiling** [comment] 2022-01-24 18:02
Hi @dengmingtong , 

Thanks for reaching out! 

Unfortunately SWB is not supported in `ap-east-1` as CloudFront access logging does not deliver logs to S3 buckets in `ap-east-1`. It's a restriction introduced by CloudFront and you can reference the "Bucket for Logs" section in [this page](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html) for more information. I'll create a ticket in our backlog to add "Supported Regions" section in our documentation. 

At the mean time, if you do find a way to successfully deploy SWB without the CloudFront logging functionality, we would love for you to contribute back to our documentation so other customers in `ap-east-1` can benefit as well. 

Thanks,
Yanyu

**Comment by dengmingtong** [comment] 2022-01-25 01:48
Hello Yanyu,

Thanks for your response.

About CloudFront access logging, I have below workround to skip it.
Comment below code in main/solution/infrastructure/config/infra/cloudformation.yml file:
        # Logging:
        #   Bucket: ${self:custom.settings.loggingBucketName}.s3.amazonaws.com
        #   Prefix: cloudfront/

Then I got the error "IllegalLocationConstraintException" error.

Could you help to check "IllegalLocationConstraintException" error? This error block the deployment in HongKong

Thanks,
Mingtong

**Comment by Bingjiling** [comment] 2022-01-25 16:49
Hi Mingtong, 

Thanks for the prompt response! I'll look into the error today and see if I can find a workaround. 

Thanks,
Yanyu

**Comment by Bingjiling** [comment] 2022-01-25 22:05
Hi Mingtong,

I found the root cause of the "IllegalLocationConstraintException" error to be a mismatch of S3 endpoint. As ap-east-1 is an opt-in region, S3 would only recognize regional endpoint, and this can be configured through S3Sync. I pushed the changes for it in this [PR](https://github.com/awslabs/service-workbench-on-aws/pull/884). 

Another issue I ran into is Cognito not supported in ap-east-1. And for this one, you can set config value `enableNativeUserPoolUsers: false` in your config file so that Cognito would not be called to create native user pool. When Cognito is disabled, internal-auth will be used for the deployment. However, we plan to fully deprecate internal-auth with v5.0.0 so this workaround would not be available for version 5.0.0 and up. 

Please try out the above two fixes and let me know if it works for you. 

Thanks,
Yanyu

**Comment by Bingjiling** [comment] 2022-01-28 19:36
Update: Resolving this ticket as @dengmingtong was able to deploy to HongKong region successfully with the fix.

**Closed as completed by Bingjiling** 2022-01-28 19:36 UTC
Labels: customer-inquiry
