### ISSUE TITLE
[Bug] No way to choose or enter Configuration during the creation of a workspace

### ISSUE THREAD

**Issue by BoPeng** [awslabs/service-workbench-on-aws#1104] opened 2023-01-16 18:23 UTC
**Describe the bug**
When I try to create a workplace, the `Configuration" item is blank and does not allow the entering or selection of configurations.

**To Reproduce**
This is a new (testing) workbench installation, and I have just created an index, a project, associated project with my own user (admin). I then went to AWS Service Catalog Products, imported EMR-v1, and create a configuration. Then, when I try to create a workplace, I cannot specify any configuration there.

**Expected behavior**
If there is no valid configuration, "create workplace" should not be allowed in the first place. If the form is created, a valid error message should be given.

**Screenshots**
<img width="653" alt="image" src="https://user-images.githubusercontent.com/9889312/212744235-e30df0b5-f6e5-464c-bb41-d8d05806ef3f.png">

<img width="872" alt="image" src="https://user-images.githubusercontent.com/9889312/212744277-89f4b7af-98b0-44fa-9bd5-75e9cc477513.png">

<img width="1683" alt="image" src="https://user-images.githubusercontent.com/9889312/212744340-2a9030ae-ca18-44ae-8766-c77d1bd9f4f9.png">

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/9889312/212744452-8199a84b-d53e-473b-8358-fdc17a6119fa.png">

**Versions (please complete the following information):**
 - Release Version installed : v5.2.5
 - Is the deployment from a forked version of the repository? no.

**Comment by pbabz** [comment] 2023-01-17 18:05
Hi Bo, thanks for reaching out
I think the issue you are experiencing is that the user who is trying to create the workspace doesn't have access rights to that config. 

When I try to create a workspace for a config I don't have access to (ie. is not available to admin), I see what you are seeing.
When I try to create a workspace with an invalid config (ie. giberish for the AMI Id), there is a config available to select. When there is no config for the environment type, I see the following:

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/112134735/212975001-a39ce150-ecc3-4e6a-a1ae-980ef6b72641.png">

I suggest you ensure that your user has access create workspaces with that config type (ie. if the user is 'admin' ensure that 'admin' is selected on the allowed roles for the config). I will add an item to the backlog to improve the UX in this scenario

**Comment by BoPeng** [comment] 2023-01-17 18:20
Thanks @pbabz . I went to `Access Control` of the configuration, added `admin` to the Roles Allowed, and now I can see the configuration for the creation of the workplace.

The problem was that I assumed `admin` has the privilege to access any configuration so I only added `researcher` in `Roles Allowed`.

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/9889312/212979202-8437f76e-1311-4672-a62c-8aaaa5e6d428.png">

The UI is a bit confusing on this so I will keep the ticket open.

**Comment by maghirardelli** [comment] 2023-01-25 14:55
Hi @BoPeng!

This is the expected behavior of SWB. Customers must explicitly declare what roles may use the workspace configuration. We do not have a default privilege for admins to see workspace configurations. I am going to close this ticket as this is not a bug and the UI clearly states "User roles allowed to launch workspaces with this Configuration" in the Access Control panel.

Thank you!
Mar

**Closed as completed by maghirardelli** 2023-01-25 14:55 UTC
Labels: bug, Review One, Review Two

**Comment by BoPeng** [comment] 2023-01-25 16:33
Well, again, showing a form with a field that does not allow any user input, and show an error message after the form is submitted is a UI/UX bug that should be fixed.
