### ISSUE TITLE
[Bug] Access toggle doesn't work when registering a study for Data Source

### ISSUE THREAD

**Issue by ElenaKosobrodova** [awslabs/service-workbench-on-aws#1042] opened 2022-09-29 23:16 UTC
**Describe the bug**
When I register a study for Data Source, 'Access' toggle should allow me to chose between 'read-only' and 'read-write' access. But the only available option is 'read-only'. The toggle doesn't work.

Also, to get access to a bucket in a hosting account, I had to manually add hosting account root to trust relationship of the IAM role created after the study registration is finished

**To Reproduce**
1. Go to 'Data Sources'
2. Click on 'Register Studies'
3. Click on 'Next'
4. Fill in the form
5. Click on 'Add Study'
7. Scroll down to 'Access' toggle
8. Click on 'Read&Write`

**Expected behavior**
The toggle should allow to chose between 'read-only' and 'read-write' access.

**Screenshots**
![image](https://user-images.githubusercontent.com/47466926/193157018-a654df66-236a-41dd-a814-66863ea82b6f.png)

**Versions (please complete the following information):**
 - Release Version installed [e.g. v1.0.3]
 v5.0.0

**Additional context**

**Comment by kpark277** [comment] 2022-10-03 18:01
Hi @ElenaKosobrodova,

I am currently unable to reproduce the issue with being unable to select "Read & Write" when testing with version 5.2.2 in both Firefox and Chrome. What browser were you using when encountering this bug and is upgrading your SWB version an option?

Regarding having to manually add the trust relationship to the IAM role, what role is this in regards to? There should be no need to add the hosting account as a trusted entity manually to any role; the workspace role should be able to access the study as the bucket policy containing the study should be updated to allow the hosting account to access it.

**Comment by ElenaKosobrodova** [comment] 2022-10-11 08:17
Hi,

We are using version 5.0.0. It looks like the issue is fixed in version
5.2.2. Thank you.

During study registration, a new stack with IAM role and IAM policy is
created. This IAM role has permissions to read objects from the bucket
which is used as a data source. When I create this bucket in the main
account, I have no problem with reading the objects. When I create the
bucket in a hosting account, the access is denied. The bucket policy of the
data source bucket was not updated. Probably, because I haven't added it
before study registration. It would be great to add checking if the policy
exists and create it if it doesn't exist or update it if it's in place.

Best regards,
Elena

**Comment by maghirardelli** [comment] 2022-10-11 13:19
Hi @ElenaKosobrodova! Are you able to upgrade to v5.2.2? If so, is it okay if I mark this issue as closed as it is fixed in a newer version of SWB?

Thanks,
Marianna

**Comment by ElenaKosobrodova** [comment] 2022-10-11 21:46
Hi Marianna. Please, go ahead and mark the issue as closed.
Best regards,
Elena

**Closed as completed** 2022-10-12 13:11 UTC
Labels: bug, Review One, Review Two
