### ISSUE TITLE
creating a study fails with "t.forEach is not a function"

### ISSUE THREAD

**Issue by zaro0508** [awslabs/service-workbench-on-aws#303] opened 2021-02-12 18:49 UTC
I have installed a fresh SC workbench. I can login and browse around. I can add an AWS account, setup an index, setup a project, associate it with an index and assign a project admin user to it. I "import" the EC2 Linux-v1 product into "workspace types".   Now I'm attempting to create a study.  When I create a study [I get an error](https://pasteboard.co/JO3aST4.png) "We have a problem! t.forEach is not a function".  I've deployed SC workbench from master branch (1977d2c6).

➜ node --version
v15.5.1

➜ pnpm --version
5.17.1

➜ go version
go version go1.12.9 darwin/amd64

**Comment by SanketD92** [comment] 2021-02-12 21:23
Hello, this has been fixed [recently](https://github.com/awslabs/service-workbench-on-aws/pull/301) and the fix was merged to the mainline branch.

**Comment by zaro0508** [comment] 2021-02-12 22:18
which one is the `mainline`? is that the `master` branch or one of the other branches?   I believe I deployed sc workbench from the master branch at the commit SHA i indicated in the issue description.

**Comment by carvantes** [comment] 2021-02-12 22:31
Apologies, there's no `mainline` branch. @SanketD92 meant the `master` branch.

The commit that fixes the issue is: https://github.com/awslabs/service-workbench-on-aws/commit/0dccba001459da8abb4cc938f024020b40e61241

**Comment by carvantes** [comment] 2021-02-15 17:08
I'm closing this issue now. Feel free to reopen if you still see issues after deploying the above fix.

**Closed by carvantes** 2021-02-15 17:08 UTC
