### ISSUE TITLE
[Misc] deployment fails as serverless v4 requires a license

### ISSUE THREAD

**Issue by mrgum** [awslabs/service-workbench-on-aws#1253] opened 2024-05-23 08:55 UTC
**What's on your mind?**
swb uses serverless to deploy the solution. the version of serverless is not pinned and serverless v4 has been released and requires a license to use it so deployments fail unless you have a account/key

For a quick fix I think any references to serverless in deploy scripts should change to serverless@^3.34.0 (or serverless@"^3.34.0" in case anyone deploys from windows)

A better, but much more involved, fix would be to use CDK to deploy the app rather than serverless.

**Versions (please complete the following information):**
I presume any version, v6.2.2 is where I'm seeing it

**Comment by dcloud9** [comment] 2024-05-23 12:45
Also, hit this issue 2 days ago. [Serverless](https://github.com/serverless/serverless/blob/4.0.24/README.md) is now a paid subscription model to use their product. I also pinned the the `npm install -g serverless@^3.38.0` and even pinned `frameworkVersion: '3.38.0'` in all `serverless.yml` files, but still `v4.0.23` is being pullled by the deployment and breaks the automation due to this login/lic key required.
![Screenshot from 2024-05-22 13-03-41](https://github.com/awslabs/service-workbench-on-aws/assets/5338204/9d7beebf-a8b6-4251-8fd7-4082288cd406)

```
[ec2-user@x.x.x.x swb]$ serverless --version
Framework Core: 3.38.0
Plugin: 7.2.3
SDK: 4.5.1
```
Error in `environment-deploy.sh <stage_name>`
```
Packages: +47
+++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 47, reused 47, downloaded 0, added 47, done


✖ Failed to resolve variable 'custom.settings.awsRegionShortName' with resolver 'config' and provider 'self': Error: Key "custom.settings.awsRegionShortName" is not defined in config file
Error: Failed to resolve variable 'custom.settings.awsRegionShortName' with resolver 'config' and provider 'self': Error: Key "custom.settings.awsRegionShortName" is not defined in config file
    at #resolveKey (file:///home/ec2-user/.serverless/releases/4.0.23/package/dist/sf-core.js:988:16637)
    at _ResolverManager.resolve (file:///home/ec2-user/.serverless/releases/4.0.23/package/dist/sf-core.js:988:21457)
    at #handlePlaceholderNode (file:///home/ec2-user/.serverless/releases/4.0.23/package/dist/sf-core.js:988:20405)
    at file:///home/ec2-user/.serverless/releases/4.0.23/package/dist/sf-core.js:988:18566
    at processNodeAndHandleCompletion (file:///home/ec2-user/.serverless/releases/4.0.23/package/dist/sf-core.js:988:13822)
    at processNodeAndManagePromise (file:///home/ec2-user/.serverless/releases/4.0.23/package/dist/sf-core.js:988:14458)
    at file:///home/ec2-user/.serverless/releases/4.0.23/package/dist/sf-core.js:988:14275
    at Array.forEach (<anonymous>)
    at processSinks (file:///home/ec2-user/.serverless/releases/4.0.23/package/dist/sf-core.js:988:14230)
    at processGraphInParallel (file:///home/ec2-user/.serverless/releases/4.0.23/package/dist/sf-core.js:988:13926)
    at #resolveAndReplacePlaceholders (file:///home/ec2-user/.serverless/releases/4.0.23/package/dist/sf-core.js:988:18289)
    at _ResolverManager.resolveAndReplacePlaceholdersInConfig (file:///home/ec2-user/.serverless/releases/4.0.23/package/dist/sf-core.js:988:18049)
    at Object.resolveServiceConfig (file:///home/ec2-user/.serverless/releases/4.0.23/package/dist/sf-core.js:988:28210)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/ec2-user/.serverless/releases/4.0.23/package/dist/sf-core.js:991:1524
    at async route (file:///home/ec2-user/.serverless/releases/4.0.23/package/dist/sf-core.js:991:1497)
```

**Comment by dcloud9** [comment] 2024-05-23 17:56
I had some leads from a colleague and tested the fix, which was suggested in this serverless [issue](https://github.com/serverless/serverless/issues/12523).
It seemed the way `serverless` is **globally** installed using `npm`  as per this [guide](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/docs/installation_guide/installation/pre-installation/instance-req.md#installing-the-required-software-on-ec2-instance) is NOT the recommended way as it'll pull the latest version. In the case of `serverless`, it'll pull `v4` Serverless Framework (version with login/license key needed).

A workaround for me (while waiting for proper fix by SWB team) is:
```
npm install serverless@3 hygen #do NOT install with -g (globally) to avoid serverless@4 breaking change
```

**Comment by SanketD92** [comment] 2024-05-23 18:11
It looks like serverless installed v4 globally on your machine, even though it shows a prior version number on the version summary. (`file:///home/ec2-user/.serverless/releases/4.0.23/package` in stack trace)

This was acknowledged as a known issue from serverless team, and they started working on rolling back v4 release.

SWB however does not use serverless v4, but was running into the same issue. We were able to confirm that deployment works after serverless rolled back v4.

**Comment by austencollins** [comment] 2024-05-23 19:47
@SanketD92 Please reach out if you still see issues here. Also, if you use `npm ls -g` you can see all globally installed npm packages on your system and what version they are.

**Comment by SanketD92** [comment] 2024-05-23 21:03
@ac360 Here's the version mismatch I'm noticing on my machine that I mentioned in the other issue:

```
(base) ➜  Service-Workbench-on-AWS git:(mainline) npm ls -g                
/Users/sdharwad/.nvm/versions/node/v18.17.1/lib
├── aws-cdk@2.130.0
├── aws-sdk-js-codemod@0.26.1
├── corepack@0.18.0
├── npm@10.2.2
└── serverless@3.34.0

(base) ➜  Service-Workbench-on-AWS git:(develop) serverless --version
Framework Core: 2.49.0
Plugin: 5.4.3
SDK: 4.2.3
Components: 3.12.0
```

I would have assumed Framework Core version in the `serverless --version` summary to match the globally installed npm version for serverless. My guess is when I first installed serverless globally it was running a 2.x.x version, but when we moved to 3.x.x it never updated the version in it's summary. Thoughts?

**Comment by SanketD92** [comment] 2024-05-24 16:19
Confirmed that the workaround mentioned [above](https://github.com/awslabs/service-workbench-on-aws/issues/1253#issuecomment-2127741944) for not installing serverless globally is the accepted solution. Closing this issue.

**Closed as completed by SanketD92** 2024-05-24 16:19 UTC
Labels: customer-inquiry, Review One, Review Two

**Comment by austencollins** [comment] 2024-05-25 00:54
@SanketD92 You can have the Framework installed globally on your machine, as well as locally in a project within the project's package.json file. In your terminal, if your current working directory has a package.json in it, or possibly in a parent directory above it, that includes the Serverless Framework, when you run `serverless` it will call it from that local installation. This could be creating the multiple version scenario you have happening. A local directory has SF V2 installed in it somewhere..
