### ISSUE TITLE
[Feature Request] Unknowable open-data and workspace region mismatch

### ISSUE THREAD

**Issue by srpiatt** [awslabs/service-workbench-on-aws#1013] opened 2022-07-11 19:50 UTC
When I launched a EC2 workspace, and selected an open-data set, I expected it to have that data available on my workspace. However, the data was not available in the region my workspace was launched in.

There should be an indication in the UI that either: warns the user that the workspace and data sets have conflicting regions, or: the data set and workspace view should display the region it's in. Currently, there's no way to tell from the ui where each data set or workspace is located, therefore the user can't know if there's a miss-alignment before deployment.

Here's the log line in syslog when SWB tried to attach the [COVID-19 Open Research Dataset (CORD-19)](https://registry.opendata.aws/cord-19/) open-data set to my EC2:
```
Jul 11 19:35:10 ip-10-192-10-20 /usr/local/bin/goofys[4261]: main.ERROR Unable to access 'ai2-semanticscholar-cord-19': BucketRegionError: incorrect region, the bucket is not in 'us-east-1' region at endpoint ''#012#011status code: 301, request id: , host id:
Jul 11 19:35:10 ip-10-192-10-20 /usr/local/bin/goofys[4261]: main.FATAL Mounting file system: Mount: initialization failed
```

**Comment by nguyen102** [comment] 2022-07-12 14:56
Thanks for your request. I've added this feature request to our backlog. We'll keep this ticket updated with any news related to the feature.

**Comment by tdmalone** [comment] 2022-07-27 11:36
This is possibly a duplicate of https://github.com/awslabs/service-workbench-on-aws/issues/1004

**Closed as completed** 2024-12-06 19:15 UTC
Labels: enhancement
