### ISSUE TITLE
[Bug] API Rate Limiting

### ISSUE THREAD

**Issue by nkitmitto** [awslabs/service-workbench-on-aws#967] opened 2022-04-11 18:33 UTC
**Describe the bug**
When loading the Workspace Types page, we get an error "Something went wrong".  This only occurs with >30 workspace types.  

**To Reproduce**
1. Login as admin
2. Go to Workspace Types
3. Where the "Not imported yet" workspace types are, you'll get a Something Went Wrong error after about 15 seconds.

**Expected behavior**
Ability to import workspace types.

**Versions (please complete the following information):**
 - Release Version installed 3.3.1

**Additional context**
Through X-Ray, it appears the app is getting API Rate limited when it called `servicecatalog:DescribeProvisioningParameters`.  
I believe this is the line causing the error: https://github.com/awslabs/service-workbench-on-aws/blob/mainline/addons/addon-environment-sc-api/packages/environment-type-mgmt-services/lib/environment-type/env-type-candidate-service.js#L154

**Comment by Bingjiling** [comment] 2022-04-13 17:51
Hi @nkitmitto ,

Thanks for reaching out! We're working on pagination to address scaling issues in SWB, and a ticket has been created in the backlog for this specific issue.

Thanks,
Yanyu

**Comment by tdmalone** [comment] 2022-07-27 11:45
This might be a duplicate of https://github.com/awslabs/service-workbench-on-aws/issues/937

**Closed as completed** 2024-12-06 19:15 UTC
Labels: bug, scaling, Review One, Review Two
